/*
 * Amro Abdelrhman
 * 01/10/2019
 * this is the multiple choice sumitive program
 */

/**
 *
 * @author amabd7808
 */
public class multiplechoice extends javax.swing.JFrame {

    /**
     * Creates new form multiplechoice
     */
    public multiplechoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tiltle = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        q1 = new javax.swing.JLabel();
        a11 = new javax.swing.JLabel();
        a12 = new javax.swing.JLabel();
        a13 = new javax.swing.JLabel();
        a14 = new javax.swing.JLabel();
        q1a = new javax.swing.JTextField();
        q2 = new javax.swing.JLabel();
        a21 = new javax.swing.JLabel();
        a22 = new javax.swing.JLabel();
        a23 = new javax.swing.JLabel();
        a24 = new javax.swing.JLabel();
        q2a = new javax.swing.JTextField();
        q3 = new javax.swing.JLabel();
        a31 = new javax.swing.JLabel();
        a32 = new javax.swing.JLabel();
        a33 = new javax.swing.JLabel();
        a34 = new javax.swing.JLabel();
        q3a = new javax.swing.JTextField();
        q4 = new javax.swing.JLabel();
        a41 = new javax.swing.JLabel();
        a42 = new javax.swing.JLabel();
        q4a = new javax.swing.JTextField();
        q5 = new javax.swing.JLabel();
        a51 = new javax.swing.JLabel();
        a52 = new javax.swing.JLabel();
        a53 = new javax.swing.JLabel();
        a54 = new javax.swing.JLabel();
        q5a = new javax.swing.JTextField();
        correctans = new javax.swing.JTextField();
        wrongans = new javax.swing.JTextField();
        mark = new javax.swing.JTextField();
        comment = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tiltle.setFont(new java.awt.Font("Zurich Blk Win95BT", 0, 18)); // NOI18N
        tiltle.setForeground(new java.awt.Color(255, 51, 51));
        tiltle.setText("multiple choice quiz");

        title2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        title2.setText("Type the number of the answer in the space provided");

        q1.setFont(new java.awt.Font("Zurich Blk Win95BT", 0, 11)); // NOI18N
        q1.setText("Q1. what is the name of our computer science teacher??");

        a11.setText("1. Mr.Abdelrhman");

        a12.setText("2. Mr.Gates");

        a13.setText("3. Mr.Kaune");

        a14.setText("4. Mr.Bates");

        q2.setFont(new java.awt.Font("Zurich Blk Win95BT", 0, 11)); // NOI18N
        q2.setText("Q2. what room does our computer science class take place??");

        a21.setText("1. Room 302");

        a22.setText("2. Room 303");

        a23.setText("3. Room 304");

        a24.setText("4. Room 305");

        q3.setFont(new java.awt.Font("Zurich Blk Win95BT", 0, 11)); // NOI18N
        q3.setText("Q3. How many computers for students is there in the computer science class??");

        a31.setText("1. 30 computers");

        a32.setText("2. 31 computers");

        a33.setText("3. 33 computers");

        a34.setText("4. 34 computers");

        q4.setFont(new java.awt.Font("Zurich Blk Win95BT", 0, 11)); // NOI18N
        q4.setText("Q4. the internet was created by the World government??");

        a41.setText("1. True");

        a42.setText("2. False ");

        q5.setFont(new java.awt.Font("Zurich Blk Win95BT", 0, 11)); // NOI18N
        q5.setText("Q5. How many keys is there in the keyboard that we use in school?? ");

        a51.setText("1.132 keys");

        a52.setText("2. 116 keys");

        a53.setText("3. 108 keys ");

        a54.setText("4. 104 keys");

        comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentActionPerformed(evt);
            }
        });

        calculate.setText("Calculate my mark");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(q3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(q3a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tiltle)
                            .addComponent(title2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a21)
                                .addGap(41, 41, 41)
                                .addComponent(a22)
                                .addGap(35, 35, 35)
                                .addComponent(a23)
                                .addGap(28, 28, 28)
                                .addComponent(a24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q1a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a41)
                                        .addGap(65, 65, 65)
                                        .addComponent(a42)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(q4a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q2a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a31)
                                .addGap(18, 18, 18)
                                .addComponent(a32)
                                .addGap(18, 18, 18)
                                .addComponent(a33)
                                .addGap(18, 18, 18)
                                .addComponent(a34)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(a11)
                        .addGap(18, 18, 18)
                        .addComponent(a12)
                        .addGap(36, 36, 36)
                        .addComponent(a13)
                        .addGap(31, 31, 31)
                        .addComponent(a14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(q5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q5a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(a51)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correctans, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a52)
                                .addGap(37, 37, 37)
                                .addComponent(a53)
                                .addGap(35, 35, 35)
                                .addComponent(a54))
                            .addComponent(wrongans, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(calculate)
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tiltle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1)
                    .addComponent(q1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a11)
                    .addComponent(a12)
                    .addComponent(a13)
                    .addComponent(a14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2)
                    .addComponent(q2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a21)
                    .addComponent(a22)
                    .addComponent(a23)
                    .addComponent(a24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3)
                    .addComponent(q3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a31)
                    .addComponent(a32)
                    .addComponent(a33)
                    .addComponent(a34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4)
                    .addComponent(q4a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a41)
                    .addComponent(a42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5)
                    .addComponent(q5a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a51)
                    .addComponent(a52)
                    .addComponent(a53)
                    .addComponent(a54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(correctans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrongans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
    // variables for the answers of the user
        int answerone;
        int answertwo;
        int answerthree;
        int answerfour;
        int answerfive;
    // variables for the mark of the user
        int firstMark;
        int secondMark;
        int thirdMark;
        int fourthMark;
        int fifthMark;
        int totalMark;
    // variable for percentage
        double per;
    // variables for right answers
        int firstrans;
        int secondrans;
        int thirdrans;
        int fourthrans;
        int fifthrans;
        int ansright;
    // variables for wrong answers
        int firstwans;
        int secondwans;
        int thirdwans;
        int fourthwans;
        int fifthwans;
        int answrong;
        answerone = Integer.parseInt(q1a.getText());
        answertwo = Integer.parseInt(q2a.getText());
        answerthree = Integer.parseInt(q3a.getText());
        answerfour = Integer.parseInt(q4a.getText());
        answerfive = Integer.parseInt(q5a.getText());
        if (answerone == 3)
        {
            firstMark = 1;
            firstrans = 1;
            firstwans = 0;
        }
        else
        {
            firstMark = 0;
            firstwans = 1;
            firstrans = 0;

        }

        if (answertwo == 2)
        {
            secondMark = 1;
            secondrans = 1;
            secondwans = 0;
        }
        else
        {
            secondMark = 0;
            secondwans = 1;
            secondrans = 0;
        }

        if (answerthree == 4)
        {
            thirdMark = 1;
            thirdrans = 1;
            thirdwans = 0;
        }
        else
        {
            thirdMark = 0;
            thirdwans = 1;
            thirdrans = 0;
        }

        if (answerfour == 2)
        {
            fourthMark = 1;
            fourthrans = 1;
            fourthwans = 0;
        }
        else
        {
            fourthMark = 0;
            fourthwans = 1;
            fourthrans = 0;
        }

        if (answerfive == 4)
        {
            fifthMark = 1;
            fifthrans = 1;
            fifthwans = 0;
        }
        else
        {
            fifthMark = 0;
            fifthwans = 1;
            fifthrans = 0;
        }

        totalMark = firstMark + secondMark + thirdMark + fourthMark + fifthMark ;
        ansright = firstrans + secondrans + thirdrans + fourthrans + fifthrans ;
        answrong = firstwans + secondwans + thirdwans + fourthwans + fifthwans ;
        correctans.setText("you got "+ansright+" right answers") ;
        wrongans.setText("you got "+answrong+" wrong answers") ;
        if (totalMark == 0)
        {
            comment.setText("nooooo that is not good, study more for next time");
            per = 0.0;
        }
        else if (totalMark == 1)
        {
            comment.setText("what!! are you series I am sure you can do way better");
            per = 20.0;
        }
        else if (totalMark == 2)
        {
            comment.setText("not good, not good go back to grade 1 then ");
            per = 40.0;
        }
        else if (totalMark == 3)
        {
            comment.setText("not bad, not bad but you can still do better ");
            per = 60.0;
        }
        else if (totalMark == 4)
        {
            comment.setText("very good you just missed one but it is okay ");
            per = 80.0;
        }
        else 
        {
            comment.setText("perfect you got into Harverd ");
            per = 100.0;
        }
        mark.setText("you got "+totalMark+"/5 which means "+per+"%");
    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(multiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(multiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(multiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(multiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new multiplechoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a11;
    private javax.swing.JLabel a12;
    private javax.swing.JLabel a13;
    private javax.swing.JLabel a14;
    private javax.swing.JLabel a21;
    private javax.swing.JLabel a22;
    private javax.swing.JLabel a23;
    private javax.swing.JLabel a24;
    private javax.swing.JLabel a31;
    private javax.swing.JLabel a32;
    private javax.swing.JLabel a33;
    private javax.swing.JLabel a34;
    private javax.swing.JLabel a41;
    private javax.swing.JLabel a42;
    private javax.swing.JLabel a51;
    private javax.swing.JLabel a52;
    private javax.swing.JLabel a53;
    private javax.swing.JLabel a54;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField comment;
    private javax.swing.JTextField correctans;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mark;
    private javax.swing.JLabel q1;
    private javax.swing.JTextField q1a;
    private javax.swing.JLabel q2;
    private javax.swing.JTextField q2a;
    private javax.swing.JLabel q3;
    private javax.swing.JTextField q3a;
    private javax.swing.JLabel q4;
    private javax.swing.JTextField q4a;
    private javax.swing.JLabel q5;
    private javax.swing.JTextField q5a;
    private javax.swing.JLabel tiltle;
    private javax.swing.JLabel title2;
    private javax.swing.JTextField wrongans;
    // End of variables declaration//GEN-END:variables
}
